import "./globals.css";
import NavBar from "./ui/navbar";
import { montserrat } from "./ui/fonts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="!scroll-smooth">
      <body className={`${montserrat.className} antialiased`}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
